name: pcc-course-enrollment-data-explorer
channels:
  - defaults
dependencies:
  - beautifulsoup4=4.11.1
  - bs4=4.11.1
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - certifi=2022.12.7
  - libffi=3.4.2
  - ncurses=6.3
  - openssl=1.1.1s
  - pip=22.3.1
  - python=3.10.8
  - readline=8.2
  - setuptools=65.5.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.0
  - tk=8.6.12
  - tzdata=2022g
  - wheel=0.37.1
  - xz=5.2.8
  - zlib=1.2.13
